Improve readability
fridaysforfuture/entschuldigungs-generator pull request #6
Opened 2019-03-15 10:35 UTC by Lergin

I have formated the text to use JS template strings instead of "normal" strings, as these allow line breaks and direct variable replacement (with `${js expression}`) so it is a lot simpler to read or edit the text. Additionally I moved the variables to use `const` instead of `var` to first remove the multiple declarations of these and make clear that these shouldn't been modified (two common pitfall for bugs).

The resulting document should look exactly the same as beforehand.

2019-03-15 18:01 UTC, karlbeecken requested changes
Much nicer coding style, but one mistake was made

2019-03-15 18:01 UTC, karlbeecken commented on js/script.js
> +  const salutation = gender === 'woman' ? 'Sehr geehrte Frau' : 'Sehr geehrter Herr'
In the HTML file stands 'women' instead of 'woman', so you have to change it here OR in the HTML, whatever you like more. When you change the HTML, please also replace 'men' with 'man' for convenience ;) 
```suggestion
  const salutation = gender === 'women' ? 'Sehr geehrte Frau' : 'Sehr geehrter Herr'
```

2019-03-15 20:54 UTC, Lergin commented
Thanks for spotting the mistake, I fixed it and solved the merge conflict :)

2019-03-15 22:20 UTC, karlbeecken approved these changes

2019-03-15 22:20 UTC, karlbeecken commented
I think female/male is a much better choice :+1:

2019-03-15 22:20 UTC, merged

2019-03-16 12:14 UTC, karlbeecken commented
@Lergin Line 95 was a very smart idea, props on this!